# Generated by Django 5.0.14 on 2025-06-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenhNhan',
            fields=[
                ('BenhNhanID', models.AutoField(primary_key=True, serialize=False)),
                ('HoVaTen', models.CharField(max_length=200)),
                ('NamSinh', models.IntegerField()),
                ('GioiTinh', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1)),
                ('Khu', models.CharField(blank=True, max_length=100, null=True)),
                ('NgayTaoHoSo', models.DateTimeField(auto_now_add=True)),
                ('TrangThai', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
