# Generated by Django 5.0.14 on 2025-06-04 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benhnhan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhSachKham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thuoc', models.CharField(max_length=200)),
                ('NgayKham', models.DateField()),
                ('NgayTaiKham', models.DateField()),
                ('BenhNhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benhnhan.benhnhan')),
            ],
        ),
    ]
