# Generated by Django 5.0.14 on 2025-06-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benhnhan', '0002_danhsachkham'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=100)),
                ('NamSinh', models.IntegerField()),
                ('GioiTinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=3)),
                ('SDT', models.CharField(max_length=15)),
                ('ChucVu', models.CharField(max_length=100)),
                ('DiaChi', models.TextField()),
                ('TrangThai', models.CharField(choices=[('Đang làm', 'Đang làm'), ('Tạm nghỉ', 'Tạm nghỉ')], default='Đang làm', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='danhsachkham',
            name='NgayKham',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='danhsachkham',
            name='NgayTaiKham',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='danhsachkham',
            name='Thuoc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
