# Generated by Django 5.0.14 on 2025-06-06 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benhnhan', '0003_nhanvien_alter_danhsachkham_ngaykham_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenDangNhap', models.CharField(max_length=100, unique=True)),
                ('MatKhau', models.CharField(max_length=128)),
                ('SoDienThoai', models.CharField(max_length=15)),
                ('Gmail', models.EmailField(max_length=254, unique=True)),
                ('Quyen', models.CharField(choices=[('admin', 'Quản trị viên'), ('nhanvien', 'Nhân viên')], default='nhanvien', max_length=20)),
                ('NgayTao', models.DateTimeField(default=django.utils.timezone.now)),
                ('TrangThai', models.CharField(choices=[('hoatdong', 'Hoạt động'), ('ngung', 'Ngưng hoạt động')], default='hoatdong', max_length=20)),
                ('LanDangNhapCuoi', models.DateTimeField(blank=True, null=True)),
                ('MaXacNhan', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
