# Generated by Django 5.0.14 on 2025-06-10 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benhnhan', '0004_taikhoan'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhuNha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TenKhu', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TenNha', models.CharField(max_length=100)),
                ('Khu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_nha', to='benhnhan.khunha')),
            ],
            options={
                'unique_together': {('TenNha', 'Khu')},
            },
        ),
        migrations.AlterField(
            model_name='benhnhan',
            name='Khu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='benhnhan.nha'),
        ),
    ]
