# Generated by Django 5.0.14 on 2025-06-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benhnhan', '0005_khunha_nha_alter_benhnhan_khu'),
    ]

    operations = [
        migrations.AddField(
            model_name='khunha',
            name='TrangThai',
            field=models.CharField(choices=[('Hoạt động', 'Hoạt động'), ('Đang sửa', 'Đang sửa')], default='Hoạt động', max_length=20),
        ),
        migrations.AddField(
            model_name='nha',
            name='TrangThai',
            field=models.CharField(choices=[('Hoạt động', 'Hoạt động'), ('Đang sửa', 'Đang sửa')], default='Hoạt động', max_length=20),
        ),
    ]
